services:
  test-local-chat-x-core-full:
    image: duxiaohao/pm2:v1
    container_name: test-local-chat-x-core-full
    restart: always
    volumes:
      - ./:/test-local-chat-x-core-full
    working_dir: /test-local-chat-x-core-full
    entrypoint: pm2-runtime start ecosystem.config.cjs
