services:
  web-chat-x-express:
    image: duxiaohao/pm2:v1
    ports:
      - 9000:9000
    networks:
      - web-chat-x
      - docker
    container_name: web-chat-x-express
    restart: always
    volumes:
      - ./web-chat-x-express:/web-chat-x-express
    working_dir: /web-chat-x-express
    entrypoint: pm2-runtime start ecosystem.config.cjs
  web-chat-x-vue:
    image: nginx:stable-perl
    container_name: web-chat-x-vue
    networks:
      - web-chat-x
      - docker
    restart: always
    depends_on:
      - web-chat-x-express
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./web-chat-x-vue:/etc/nginx/html"
  coturn:
    image: coturn/coturn:4.6.2
    container_name: coturn-server
    ports:
      - "3478:3478"
      - "3479:3479"
      - "3478:3478/udp"
      - "3479:3479/udp"
      - "5349:5349"
      - "5350:5350"
      - "5349:5349/udp"
      - "5350:5350/udp"
      - "49160-49200:49160-49200/udp"
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf
      - ./certs:/etc/certs
    restart: always
    networks:
      - docker
      - web-chat-x
networks:
  web-chat-x:
    name: web-chat-x
    driver: bridge
  docker:
    external:
      name: docker
