/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatComponent: typeof import('./components/ChatComponent.vue')['default']
    DialogComponent: typeof import('./components/DialogComponent.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconLock: typeof import('@element-plus/icons-vue')['Lock']
    ElIconUser: typeof import('@element-plus/icons-vue')['User']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    QrcodeComponent: typeof import('./components/QrcodeComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetAboutComponent: typeof import('./components/SetAboutComponent.vue')['default']
    SetAdvancedComponent: typeof import('./components/SetAdvancedComponent.vue')['default']
    SetAudioVideoComponent: typeof import('./components/SetAudioVideoComponent.vue')['default']
    SetGeneralComponent: typeof import('./components/SetGeneralComponent.vue')['default']
    SetPrivacyComponent: typeof import('./components/SetPrivacyComponent.vue')['default']
    SetUserInfoComponent: typeof import('./components/SetUserInfoComponent.vue')['default']
    SwitchComponent: typeof import('./components/SwitchComponent.vue')['default']
    VideoAudioComponent: typeof import('./components/VideoAudioComponent.vue')['default']
    VideoComponent: typeof import('./components/overduecomponent/VideoComponent.vue')['default']
  }
}
