name: deploy web-chat-x-express libp2p stun server
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/web-chat-x-express"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.3
      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "18.18.1"
      - uses: pnpm/action-setup@v3.0.0
        name: Install pnpm
        with:
          version: 8.12.0
          run_install: false
      - name: Install npm dependencies
        run: pnpm install
      - name: Build
        run: pnpm build:b
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ vars.SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "packages/web-chat-x-express/build/"
          REMOTE_HOST: "81.68.108.130"
          REMOTE_USER: root
          TARGET: "/home/web-chat-x/web-chat-x-express"
