name: deploy web-chat-x-vue libp2p web application
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/web-chat-x-vue/**"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.3
      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "18.18.1"
      - uses: pnpm/action-setup@v3.0.0
        name: Install pnpm
        with:
          version: 9.3.0
          run_install: false
      - name: Install npm dependencies
        run: pnpm install
      - name: Build
        run: pnpm build:f
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ vars.SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "packages/web-chat-x-vue/dist/"
          REMOTE_HOST: "62.234.163.223"
          REMOTE_USER: root
          TARGET: "/home/web-chat-x/web-chat-x-vue"
